### ISSUE TITLE
Repository is not cross-platform compatible

### ISSUE THREAD

**Issue by kiddailey** [carolzbnbr/TheNextLoop.OnScreenSize#2]
When attempting to clone the repository on non-Mac OS X systems, an error occurs:

```
Clone: invalid path 'Src/TheNextLoop.Markups/.vs/TheNextLoop.Markups/xs/project-cache/TheNextLoop.Markups.iOS-Debug|iPhoneSimulator.json' unable to checkout working tree
```
It appears this is due to the pipe symbol in the filename.  This is easily resolved by removing the ".vs" folder from the repository and adding it to .gitignore as it technically is not needed.  I've already made the required changes and will submit a pull request for this issue.

**Comment by kiddailey** [comment]
Thanks for the merge.  I've confirmed that checking out Main succeeds now without any issues.

**Comment by carolzbnbr** [comment]
No problem. 

If you want a fresh version of this markup api check this out https://github.com/carolzbnbr/OnScreenSizeMarkup 

It also has nugets and soon will be pushed to Maui Community Toolkit.

**Comment by kiddailey** [comment]
Thanks!  Yes, I did see the updated version as well.  But I stumbled on this one first and figured I'd fix the issue I originally had for anyone else that might follow the same discovery path :)  Many kudos to you for a great idea and implentation!
